plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android' apply false
}

android {
    namespace 'com.hansong.orion.wakeup'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.7.0'
}
